[[main]]
  identifier = "about"
  name = "about"
  url = "about"
  weight = 1


[[main]]
  identifier = "posts"
  name = "posts"
  url = "posts"
  weight = 2
    
[[main]]
  identifier = "notes"
  name = "notes"
  url = "notes"
  weight = 3
